-- CreateEnum
CREATE TYPE "TagType" AS ENUM ('SKIN_TYPE', 'CONCERN', 'INGREDIENT', 'FEATURE', 'ROUTINE', 'TEXTURE', 'AGE_GROUP', 'SPF_TYPE', 'GENDER');

-- AlterTable
ALTER TABLE "tags" ADD COLUMN     "type" "TagType" NOT NULL DEFAULT 'SKIN_TYPE';
